const truths = [
  "Apa ketakutan terbesar kamu?",
  "Siapa orang pertama yang kamu suka?",
  "Apa rahasia terbesar yang kamu simpan dari orang tua?",
  "Pernah bohong ke teman dekat? Ceritakan.",
  "Apa momen paling memalukan di sekolah?",
  "Siapa selebriti yang kamu crush?",
  "Apa kebiasaan buruk yang sulit dihilangkan?",
  "Pernah curang di ujian? Bagaimana?",
  "Apa mimpi teraneh yang pernah kamu alami?",
  "Siapa teman yang paling kamu percaya?",
  "Apa yang paling kamu sesali dalam hidup?",
  "Pernah mencuri sesuatu? Apa itu?",
  "Apa lagu favorit yang memalukan?",
  "Siapa yang kamu hindari di pesta?",
  "Apa hobi rahasia kamu?",
  "Pernah jatuh cinta pada sahabat?",
  "Apa makanan yang kamu benci tapi pura-pura suka?",
  "Siapa guru paling menakutkan?",
  "Apa kebohongan terbesar yang pernah kamu katakan?",
  "Pernah stalking mantan di media sosial?",
  "Apa talenta tersembunyi kamu?",
  "Siapa yang paling lucu di keluarga?",
  "Apa film yang bikin kamu nangis?",
  "Pernah gagal diet? Ceritakan.",
  "Apa julukan memalukan di masa kecil?",
  "Siapa yang kamu iri?",
  "Apa buku favorit yang memalukan?",
  "Pernah berpura-pura sakit?",
  "Apa rahasia yang kamu bagi dengan satu orang saja?",
  "Siapa tetangga yang paling aneh?",
  "Apa olahraga yang kamu benci?",
  "Pernah lupa nama orang?",
  "Apa warna favorit yang berubah-ubah?",
  "Siapa idola masa kecil?",
  "Apa kebiasaan pagi yang aneh?",
  "Pernah tersesat sendirian?",
  "Apa makanan pedas yang bikin kamu menangis?",
  "Siapa teman yang paling boros?",
  "Apa lagu yang selalu kamu nyanyi salah?",
  "Pernah jatuh di depan orang banyak?",
  "Apa hewan peliharaan impian?",
  "Siapa yang paling pintar di grup?",
  "Apa mimpi karir yang gila?",
  "Pernah bohong soal umur?",
  "Apa minuman favorit yang aneh?",
  "Siapa saudara yang paling dekat?",
  "Apa hantu favorit di film?",
  "Pernah lupa kado ulang tahun?",
  "Apa superpower yang kamu inginkan?",
  "Siapa yang paling sering telat?",
  "Apa makanan manis yang bikin ketagihan?",
  "Pernah curi permen dari toko?",
  "Apa lagu dansa yang memalukan?",
  "Siapa teman yang paling pemalu?",
  "Apa liburan terburuk?",
  "Pernah berpura-pura tidur?",
  "Apa warna rambut impian?",
  "Siapa yang paling suka gosip?",
  "Apa buah favorit yang aneh?",
  "Pernah gagal masak?",
  "Apa julukan dari teman?",
  "Siapa yang paling berani?",
  "Apa film horor yang bikin takut?",
  "Pernah lupa password?",
  "Apa kebiasaan malam hari?",
  "Siapa idola musik?",
  "Apa makanan asin favorit?",
  "Pernah tersandung di tangga?",
  "Apa mimpi terburuk?",
  "Siapa yang paling rajin belajar?",
  "Apa hobi masa kecil?",
  "Pernah bohong ke dokter?",
  "Apa minuman dingin favorit?",
  "Siapa tetangga baik?",
  "Apa lagu sedih favorit?",
  "Pernah jatuh dari sepeda?",
  "Apa talenta musik?",
  "Siapa yang paling kreatif?",
  "Apa liburan impian?",
  "Pernah curi ide teman?",
  "Apa warna mata impian?",
  "Siapa saudara jauh?",
  "Apa buku petualangan favorit?",
  "Pernah lupa janji?",
  "Apa superpower terburuk?",
  "Siapa yang paling lucu?",
  "Apa makanan pedas favorit?",
  "Pernah berpura-pura sakit hati?",
  "Apa hobi membaca?",
  "Siapa teman lama?",
  "Apa film komedi terbaik?",
  "Pernah tersesat di mall?",
  "Apa kebiasaan makan?",
  "Siapa yang paling petualang?",
  "Apa lagu romantis favorit?",
  "Pernah gagal nyanyi karaoke?",
  "Apa mimpi masa depan?",
  "Siapa idola olahraga?",
  "Apa minuman panas favorit?",
  "Pernah bohong soal hobi?",
  "Apa warna baju favorit?",
  "Siapa yang paling setia?",
  "Apa buah segar favorit?",
  "Pernah jatuh cinta pertama kali?"
];

const dares = [
  "Nyanyi lagu favorit dengan suara lucu.",
  "Kirim pesan random ke kontak pertama.",
  "Lakukan 10 push-up sekarang.",
  "Panggil teman dengan nama binatang.",
  "Foto konyol dan share ke grup.",
  "Minum segelas air tanpa napas.",
  "Tari seperti ayam selama 30 detik.",
  "Ceritakan joke terburuk.",
  "Ganti wallpaper HP jadi foto memalukan.",
  "Hubungi orang tua dan bilang 'I love you'.",
  "Lakukan pose yoga aneh.",
  "Baca berita dengan suara robot.",
  "Kirim emoji random ke 5 orang.",
  "Lompat-lompat seperti kanguru.",
  "Buat puisi pendek tentang teman.",
  "Foto dengan ekspresi aneh.",
  "Nyanyi chorus lagu populer.",
  "Lakukan high-five ke udara 10 kali.",
  "Pretend kamu superhero.",
  "Kirim voice note lucu.",
  "Lakukan gerakan dansa viral.",
  "Baca kalimat ini mundur.",
  "Foto dengan barang aneh.",
  "Lakukan 5 sit-up.",
  "Panggil diri sendiri dengan nama lucu.",
  "Kirim meme ke grup.",
  "Tari twist 20 detik.",
  "Buat suara hewan.",
  "Foto selfie gelap.",
  "Lakukan handshake unik.",
  "Nyanyi dengan mata tertutup.",
  "Kirim pesan 'Halo' ke stranger (aman).",
  "Lompat bintang 5 kali.",
  "Pretend kamu chef dan masak imajiner.",
  "Baca buku dengan suara dramatis.",
  "Foto dengan pose model.",
  "Lakukan gerakan olahraga konyol.",
  "Kirim stiker lucu.",
  "Tari seperti robot.",
  "Buat rima sederhana.",
  "Foto dengan filter aneh.",
  "Lakukan 10 jumping jacks.",
  "Panggil teman 'Boss'.",
  "Nyanyi lagu anak-anak.",
  "Kirim foto makanan favorit.",
  "Lompat tali imajiner.",
  "Pretend kamu penyanyi opera.",
  "Baca pesan dengan aksen.",
  "Foto grup konyol.",
  "Lakukan pose superhero.",
  "Kirim joke via chat.",
  "Tari salsa 15 detik.",
  "Buat suara kartun.",
  "Foto dengan hewan (jika ada).",
  "Lakukan plank 10 detik.",
  "Panggil semua 'Your Majesty'.",
  "Nyanyi dengan suara tinggi.",
  "Kirim video pendek lucu.",
  "Lompat seperti katak.",
  "Pretend kamu detektif.",
  "Baca headline berita lucu.",
  "Foto dengan buku.",
  "Lakukan gerakan karate.",
  "Kirim pesan motivasi.",
  "Tari hip-hop sederhana.",
  "Buat cerita pendek.",
  "Foto dengan cermin.",
  "Lakukan 5 burpee.",
  "Panggil teman 'Captain'.",
  "Nyanyi duet imajiner.",
  "Kirim foto langit.",
  "Lompat tali nyata.",
]
const resultDiv = document.getElementById("result");
const spinner = document.getElementById("spinner");

function generateTruth() {
  showSpinner();
  setTimeout(() => {
    const index = Math.floor(Math.random() * truths.length);
    resultDiv.innerHTML = `<i class="fas fa-question-circle truth-icon"></i>
    <h2>Truth</h2> <p>${truths[index]}</p>`;
    resultDiv.classList.add("show");
    hideSpinner();
  }, 800); //loding
}

function generateDare() {
  showSpinner();
  setTimeout(() => {
    const index = Math.floor(Math.random() * dares.length);
    resultDiv.innerHTML = `<i class="fas fa-fire dare-icon"></i>
    <h2>Dare</h2> <p>${dares[index]}</p>`;
    resultDiv.classList.add("show");
    hideSpinner();
  }, 800);
}

function showSpinner() {
  spinner.classList.add("show");
  resultDiv.classList.remove("show");
}

function hideSpinner() {
  spinner.classList.remove("show");
}
